### ISSUE TITLE
Xcode 8.2 requires conversion to Swift 3

### ISSUE THREAD

**Issue by tylerjames** [macteo/Marklight#3]
I just updated to Xcode 8.2 and have been using Marklight as a Cocoapod. Upon running Xcode it requires any Swift code to be updated to Swift 3 syntax. Previously Swift 2.3 was allowed, which did not require any changes. When converting to Swift 3 the wizard will recommend many changes and the end result is that there will be many errors.

Could you please update the code for Swift 3?

**Comment by macteo** [comment]
Hello,
I've just migrated the project to Swift 3. 

fb9aebcd1375f15a919a93369ec6e3d03f537fc5

It's available on CocoaPods as version 1.0.0.

Have a nice day!
