### ISSUE TITLE
Change default text color

### ISSUE THREAD

**Issue by ivancantarino** [macteo/Marklight#30]
Hello.

I have been trying to change the `UITextView textColor` while using `MarklightTextStorage()` and I cannot achieve that.

The textView's default color keeps swapping itself to black, even if I force it to be a  specific color.

I'm wondering that this might me something within the `textStorage.marklightTextProcessor` properties.

Can I get some help on how to achieve this please?

Thanks.

**Comment by funkenstrahlen** [comment]
I also try to change this to add support for iOS 13 dark mode.
