### ISSUE TITLE
Update for Xcode 9 and Swift 4

### ISSUE THREAD

**Issue by JohJakob** [macteo/Marklight#4]
Marklight is not working with Xcode 9 and Swift 4. We should update it to work with iOS 11 and later.

**Comment by macteo** [comment]
I'll work on it as soon as possible. Thanks for the reminder.

**Comment by macteo** [comment]
Here we go: new [feature/swift4](https://github.com/macteo/Marklight/tree/feature/swift4) branch should work with Xcode 9 beta 3 and Swift 4.

acc0240ea2f2b1dd2c106e388d8e2ab7ae1e4a1f

**Comment by JohJakob** [comment]
Thanks a lot, @macteo!
